sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: OQ8qvzFb0AkXpmXAkF4tn39vy1vMw5ZBiy5BG1XUFdagYgk5JqOwOvdsWIGDW0K7RElceH1+dxTKh7xL/AT+ZOJkHZAQNMzds5grXSlb8+Ls4qcc6cArXcTBQiAkyaanL1mTRpVrePMQSQ/Ud7ubbO1pISM3g41JfYQ69Tub/2WswRoc7usZU4BLi76CgNqU7lL8AQyc92Kfdbxs5++Y0biMUg89/W5w6VoGNJGX4Sre72LlEfP69LAGFB7339d6hVvFUhQ2fCaweUP2ESrMtVJ+q/T/UoubNydUR9AiioffHslNBjRv1M15D66U4TCmJM5VQx+zMMLikcLZ2vcD4XB+E2u8ESvGE3YVLIpw+RkrodYk5HiURBXpr5xsitl3V5oD2UV14MfR7DtTl5n8ew4yzJTNnzCUX0gPQjW91VfXNlXy82/I/xfevZ3BeMb2k/08JbT/+4611ScQHvQ2W+hEgJETiuBhF49EFVAb4B29nOlFG+BiE1fbWlN98Sqj50sqF4Zq9VZZ/4ydIejiQ+HC/1urbmpR7Qyk5fQQnLyzAbTla/uBoe7xRr4id6b9U91CYuTe08fu4lkZdm+wq0nl66en3cfIQH3B6KhbbQwuYYqgibZ25Un0ntmskSIXNNfRNMhcHb002rDSsmWH7RO8pn0OeYQzyQ/HueoMAKs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Voyages-in-Search-of-the-North-West-Passage_3482
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy